### ISSUE TITLE
crash on load(1.14.4-exotic-blocks-0.4.70+1.14.4)

### ISSUE THREAD

**Issue by SDUBZ** [grondag/exotic-blocks#1]
fabric-api-0.4.0+build.240-1.14
exotic-matter-1.6.244+1.14.4
exotic-blocks-0.4.70+1.14.4
crash:
http://puu.sh/EnWGV/8da0834bab.txt

**Comment by grondag** [comment]
Fixed with [Exotic Matter build 249](https://www.curseforge.com/minecraft/mc-mods/exotic-matter-library/files/2800802)

**Comment by SDUBZ** [comment]
Thank you for all the hard work
