### ISSUE TITLE
Crash on dedi server when wedges are placed

### ISSUE THREAD

**Issue by LemmaEOF** [grondag/exotic-blocks#2]
Exotic Blocks 0.4.70+1.14.4, Exotic Matter 1.6.249, JOML Mod 1.0.0+build.8

Whenever a wedge block is placed on a dedicated server, the game will crash with `java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/joml/Vector3f`. It looks like this is because something is trying to call JOML server-side, even though JOML is client-only.

**Comment by grondag** [comment]
Thanks for the report.  There's nothing in JOML itself that should really prevent it from running server-side.  In this case it's being used (or was meant to be used) for transforming server-side collision volumes.  Was probably a mistake to mark it client-only.  Will take a look.

**Comment by grondag** [comment]
Fixed in https://github.com/grondag/exotic-matter-2/commit/0d2c3917d90eba209f528ab2ce4dc7fc1d82bf5f

Thanks again for the report.
