### ISSUE TITLE
Compatibility with Blockus

### ISSUE THREAD

**Issue by pjlasl** [grondag/exotic-blocks#6]
Could you extend your mod to be compatible with Blockus?

**Comment by grondag** [comment]
I assume you mean adding additional shape variants for Blockus blocks. Is that right? I would like to see that, too.

**Comment by pjlasl** [comment]
Yes, that is correct.

**Comment by grondag** [comment]
Unfortunately I won't be able to provide built-in Blockus support at this time.  Blockus is GPL and while I _might_ be able to implement blocks using Blockus textures as a sort of companion mod, I prefer to avoid the risk of license entanglements and having a separate mod to maintain.  

That said, it should be relatively easy for Blockus to create this integration, or for someone else to create a GPL companion mod that does so.  If anyone is interested in pursuing that, I would support with necessary hooks or answering questions as needed.
