### ISSUE TITLE
Crash when flipping through Roughly Enough Items.

### ISSUE THREAD

**Issue by crabdancing** [grondag/exotic-blocks#7]
If I flip far enough and REI gets to some particular item from XB, the rendering of it causes an instant crash.

See crashlog [here](https://gist.github.com/alxpettit/fea4b17850d425ad4e1a6e6f70606e14).

Edit: Also noteworthy that typing `@exotic` [causes the crash as well](https://paste.ee/p/Rntn5).

**Comment by grondag** [comment]
Strange. Have the same versions of my mods and REI in MutiMC and runs fine. Not clear what could be causing it.

**Comment by crabdancing** [comment]
Is there any mod or flag that'll help with it printing more information, maybe? I've done some testing, and if I clear all the other mods except the libraries & REI & the XB stuff, it works fine. So this is probably an incompatibility between this and some other mod in my modpack.

In the meantime, I've started writing a tool to make it easier to apply a binary search to find the problem mod, on ambiguous cases like this. So thanks for the new project idea! :D

**Comment by grondag** [comment]
That makes sense. I was expecting a mod compatibility issue, though this one is strange. 

XM attaches some data to block states and items but doesn’t change their functionality otherwise. Might be some changes in another mod that break those additions. 

I don’t have any creative ideas for additional logging that would help here, but if you can isolate the conflicting mod that would almost certainly point me to the problem.

**Comment by grondag** [comment]
Hmmm, I just noticed that Sodium is in the pack and despite being an excellent optimization mod it does not yet support the Fabric rendering API. XM uses that API heavily and I might be able to make it but crash but it really won’t work (no connected textures, for example) without the FRAPI. 

Could you try removing it to confirm? 

If that’s the problem, then Canvas is an alternative. But be advised it has its own compatibility issues and is not quite as fast as Sodium on most machines. (But it is fast.)

**Comment by crabdancing** [comment]
Yup! It's sodium. See crash log [here](https://gist.github.com/alxpettit/eefebf34d256697f308f29e3edbb47ce). I tried reenabling every mod in the modpack and it worked.

I suppose I should open an issue on the sodium people's issue tracker, then? :P

**Comment by grondag** [comment]
Thanks for confirming. No need to open an issue there. JellySquid knows and we are both adding checks to catch it at load time so nobody is tripped up again.

**Comment by crabdancing** [comment]
Ah okies! NP, and thanks for adding the checks! :)

**Comment by TheVillageid10t** [comment]
This saved me from being annoying, I was just about to open a new issue.

**Comment by crabdancing** [comment]
@TheVillageid10t 

I be annoying so you don't have to! ^w^
